In [1]:
import numpy as np
import time

In [2]:
arr = np.array([1,2,3,3,4,5])

In [3]:
size = 10000000

In [4]:
start = time.time()
py_list=list(range(size))
for i in py_list:
    sqr = i**2
end = time.time()
print(end-start)

3.256202459335327


In [5]:
start = time.time()
np_arr=np.array(range(size))
sqr = np_arr**2
end = time.time()
print(end-start)

2.016977548599243


In [6]:
import sys

In [7]:
#difference between the memory optimazation
print(sys.getsizeof(py_list)*len(py_list))
print(np_arr.nbytes*len(np_arr)) 

800000560000000
800000000000000


In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr,arr.dtype,arr.shape)

[ 1  2  3  4  5  6  7  8  9 10] int64 (10,)


In [9]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10,"hello"])
print(arr2,arr2.dtype,arr2.shape)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' 'hello'] <U21 (11,)


In [10]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2d,arr2d.dtype,arr2d.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] int64 (4, 3)


In [11]:
arr = np.zeros((3,3), dtype = "int64")  #create a zeros array
print(arr,arr.shape)


[[0 0 0]
 [0 0 0]
 [0 0 0]] (3, 3)


In [12]:
arr2 = np.ones((3,3))                     ##create a ones array
print(arr2)
print(arr2.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)


In [13]:
arr3 = np.eye(4)                       ##create a indentical array
print(arr3,arr3.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)


In [14]:
arr4 = np.full((3,3),84)                 ##create a full array as your wish
print(arr4,arr4.shape)

[[84 84 84]
 [84 84 84]
 [84 84 84]] (3, 3)


In [15]:
arr5 = np.arange(1,11)                    ##create a linear array to youe suggestion
print(arr5,arr5.shape)

[ 1  2  3  4  5  6  7  8  9 10] (10,)


In [16]:
arr6 = np.linspace(1,100,6,dtype="int64")             ##create a random array with your wish how can array limit set
print(arr6)
print(arr6.shape)

[  1  20  40  60  80 100]
(6,)


In [17]:
arr = np.array([1,2,3,4,4,5,6,4,5,6,7,9])                   #type casting also allow 
print(arr,arr.dtype)
arr2 = arr.astype(np.float64)
print(arr2,arr2.dtype)

[1 2 3 4 4 5 6 4 5 6 7 9] int64
[1. 2. 3. 4. 4. 5. 6. 4. 5. 6. 7. 9.] float64


In [26]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[23,34,22]])
print(arr.shape)
# new =arr.reshape((3,4))    # one dimension to another dimensions
# new2 =arr.flatten()         # convert and dimension array into 1d array

# print(arr)
# print(new)
# print(new2,new2.shape)

print(arr.sum())

(4, 3)
124


In [19]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[23,34,22]])
arr = np.array([1,2,3,4,5,6,7,8,9])  

print(arr[5])
print(arr2[1][2])

print(arr[[1,3,4]])
print(arr[arr>4])

print(arr[1:6])       #sicing

6
6
[2 4 5]
[5 6 7 8 9]
[2 3 4 5 6]


In [20]:
arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3].copy()   #to create the copy   most imp to knows
print (sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]


In [31]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

new =np.sum(arr2d,axis = 0)  #column sum
print(new)

new =np.sum(arr2d,axis = 1)   # row sum
print(new)

#slcing

print(arr2d[0:2,1:2])

[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [22]:
arr3d =np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])

print(arr3d,arr3d.shape)
print(arr3d[0,1,1])

newarr=arr3d[:,0,:]=84
print(newarr)
print(arr3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
84
[[[84 84]
  [ 3  4]
  [ 5  6]]

 [[84 84]
  [ 9 10]
  [11 12]]]


In [23]:
arr = np.array([[1, 2], [3, 4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr);

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
